### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ReikonKarite** [ReikonKarite/MTGProj#1]
- [x] Get all cards navigable by page
- [x] Get specific card via link on index page
- [x] get all sets
- [x] get specific set using set code query string
- [ ] code cleanliness 
- [ ] Booster Simulation
- [x] UI for Cards and cardlist
- [ ] UI for setlist and set
- [ ] UI for booster simulation
- [ ] Deckbuilder
